server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # Server 1 Route
        - id: Server-1
          uri: http://localhost:8081
          predicates:     # I use the Path predicate
          - Path=/ser1/**
          filters:     # I use the RewritePath filter
          - RewritePath=home, homeV2

        # Server 2 Route
        - id: Server-2
          uri: http://localhost:8082
          predicates:     # I use the Path predicate
            - Path=/ser2/**

#     The Server-1 route will match any requests having the
# path “/ser1/**”, rewrite the “home” string in the path
# into the “homeV2” string in the path and then forward
# requests to http://localhost:8081. If the GatewayService
# service receive any requests having the path “/ser1/home”,
# it will modify and forward that request with the new path
# “/ser1/homeV2” to http://localhost:8081.